version: 3.8

services:
  db:
    image: postgres:latest
    container_name: autonix_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autonix
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  kafka:
    image: apache/kafka
    container_name: autonix_kafka
    restart: always
    ports:
      - "9092:9092"

volumes:
  db_data: